2025-04-03 17:08:41,735 INFO    MainThread:1858433 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-03 17:08:41,735 INFO    MainThread:1858433 [wandb_setup.py:_flush():67] Configure stats pid to 1858433
2025-04-03 17:08:41,735 INFO    MainThread:1858433 [wandb_setup.py:_flush():67] Loading settings from /home/kosie011/.config/wandb/settings
2025-04-03 17:08:41,735 INFO    MainThread:1858433 [wandb_setup.py:_flush():67] Loading settings from /home/kosie011/OccupancyFlow/wandb/settings
2025-04-03 17:08:41,735 INFO    MainThread:1858433 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-03 17:08:41,736 INFO    MainThread:1858433 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/kosie011/OccupancyFlow/wandb/run-20250403_170841-gvgtv1bn/logs/debug.log
2025-04-03 17:08:41,736 INFO    MainThread:1858433 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/kosie011/OccupancyFlow/wandb/run-20250403_170841-gvgtv1bn/logs/debug-internal.log
2025-04-03 17:08:41,736 INFO    MainThread:1858433 [wandb_init.py:init():781] calling init triggers
2025-04-03 17:08:41,736 INFO    MainThread:1858433 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'tfrecord_path': '../data1/waymo_dataset/uncompressed/tf_example/validation', 'idx_path': '../idx/validation', 'batch_size': 14, 'batches_per_epoch': 1, 'epochs': 10, 'lr': 0.001, 'weight_decay': 0, 'gamma': 0.999, 'road_map_image_size': 224, 'trajectory_feature_dim': 10, 'motion_encoder_hidden_dim': 512, 'motion_encoder_seq_len': 11, 'flow_field_hidden_dim': 512, 'flow_field_fourier_features': 128, 'token_dim': 768, 'embedding_dim': 1024, '_wandb': {}}
2025-04-03 17:08:41,736 INFO    MainThread:1858433 [wandb_init.py:init():809] starting backend
2025-04-03 17:08:41,736 INFO    MainThread:1858433 [wandb_init.py:init():813] sending inform_init request
2025-04-03 17:08:41,741 INFO    MainThread:1858433 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-03 17:08:41,741 INFO    MainThread:1858433 [wandb_init.py:init():823] backend started and connected
2025-04-03 17:08:41,744 INFO    MainThread:1858433 [wandb_init.py:init():915] updated telemetry
2025-04-03 17:08:41,749 INFO    MainThread:1858433 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-03 17:08:41,959 INFO    MainThread:1858433 [wandb_init.py:init():1014] starting run threads in backend
2025-04-03 17:08:42,042 INFO    MainThread:1858433 [wandb_run.py:_console_start():2454] atexit reg
2025-04-03 17:08:42,045 INFO    MainThread:1858433 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-03 17:08:42,045 INFO    MainThread:1858433 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-03 17:08:42,045 INFO    MainThread:1858433 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-03 17:08:42,047 INFO    MainThread:1858433 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-03 17:14:14,176 WARNING MsgRouterThr:1858433 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/home/kosie011/ofenv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kosie011/ofenv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kosie011/ofenv/lib/python3.11/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kosie011/ofenv/lib/python3.11/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/kosie011/ofenv/lib/python3.11/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-03 17:14:14,180 INFO    MsgRouterThr:1858433 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
